/*
 * Decompiled with CFR 0.145.
 */
package org.apache.xpath.res;

import java.util.ListResourceBundle;
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

public class XPATHErrorResources
extends ListResourceBundle {
    public static final String BAD_CODE = "BAD_CODE";
    public static final String ERROR0000 = "ERROR0000";
    public static final String ERROR_HEADER = "Error: ";
    public static final String ERROR_RESOURCES = "org.apache.xpath.res.XPATHErrorResources";
    public static final String ERROR_STRING = "#error";
    public static final String ER_ARG_CANNOT_BE_NULL = "ER_ARG_CANNOT_BE_NULL";
    public static final String ER_ASNODEITERATOR_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER = "ER_ASNODEITERATOR_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER";
    public static final String ER_AXES_NOT_ALLOWED = "ER_AXES_NOT_ALLOWED";
    public static final String ER_BOOLEAN_ARG_NO_LONGER_OPTIONAL = "ER_BOOLEAN_ARG_NO_LONGER_OPTIONAL";
    public static final String ER_CANNOT_CALL_SETSHOULDCACHENODE = "ER_CANNOT_CALL_SETSHOULDCACHENODE";
    public static final String ER_CANNOT_CREATE_URL = "ER_CANNOT_CREATE_URL";
    public static final String ER_CANNOT_DEAL_XPATH_TYPE = "ER_CANNOT_DEAL_XPATH_TYPE";
    public static final String ER_CANNOT_WRITE_TO_EMPTYNODELISTIMPL = "ER_CANNOT_WRITE_TO_EMPTYNODELISTIMPL";
    public static final String ER_CANT_CONVERT_TO_BOOLEAN = "ER_CANT_CONVERT_TO_BOOLEAN";
    public static final String ER_CANT_CONVERT_TO_MUTABLENODELIST = "ER_CANT_CONVERT_TO_MUTABLENODELIST";
    public static final String ER_CANT_CONVERT_TO_NODELIST = "ER_CANT_CONVERT_TO_NODELIST";
    public static final String ER_CANT_CONVERT_TO_NUMBER = "ER_CANT_CONVERT_TO_NUMBER";
    public static final String ER_CANT_CONVERT_TO_SINGLENODE = "ER_CANT_CONVERT_TO_SINGLENODE";
    public static final String ER_CANT_CONVERT_TO_STRING = "ER_CANT_CONVERT_TO_STRING";
    public static final String ER_CANT_CONVERT_TO_TYPE = "ER_CANT_CONVERT_TO_TYPE";
    public static final String ER_CANT_CONVERT_XPATHRESULTTYPE_TO_NUMBER = "ER_CANT_CONVERT_XPATHRESULTTYPE_TO_NUMBER";
    public static final String ER_CANT_GET_SNAPSHOT_LENGTH = "ER_CANT_GET_SNAPSHOT_LENGTH";
    public static final String ER_CONTEXT_HAS_NO_OWNERDOC = "ER_CONTEXT_HAS_NO_OWNERDOC";
    public static final String ER_COULDNOT_BE_FORMATTED_TO_NUMBER = "ER_COULDNOT_BE_FORMATTED_TO_NUMBER";
    public static final String ER_COULDNOT_CREATE_XMLPROCESSORLIAISON = "ER_COULDNOT_CREATE_XMLPROCESSORLIAISON";
    public static final String ER_COULDNOT_FIND_ENDOP_AFTER_OPLOCATIONPATH = "ER_COULDNOT_FIND_ENDOP_AFTER_OPLOCATIONPATH";
    public static final String ER_COULDNOT_FIND_FUNCTION = "ER_COULDNOT_FIND_FUNCTION";
    public static final String ER_COULDNOT_GET_VAR_NAMED = "ER_COULDNOT_GET_VAR_NAMED";
    public static final String ER_COULD_NOT_FIND_VAR = "ER_COULD_NOT_FIND_VAR";
    public static final String ER_COUNT_TAKES_1_ARG = "ER_COUNT_TAKES_1_ARG";
    public static final String ER_CURRENT_NOT_ALLOWED_IN_MATCH = "ER_CURRENT_NOT_ALLOWED_IN_MATCH";
    public static final String ER_CURRENT_TAKES_NO_ARGS = "ER_CURRENT_TAKES_NO_ARGS";
    public static final String ER_DETACH_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER = "ER_DETACH_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER";
    public static final String ER_DIDNOT_FIND_XPATH_SELECT_EXP = "ER_DIDNOT_FIND_XPATH_SELECT_EXP";
    public static final String ER_DOCUMENT_REPLACED = "ER_DOCUMENT_REPLACED";
    public static final String ER_DOC_MUTATED = "ER_DOC_MUTATED";
    public static final String ER_DTM_CANNOT_HANDLE_NODES = "ER_DTM_CANNOT_HANDLE_NODES";
    public static final String ER_EMPTY_EXPRESSION = "ER_EMPTY_EXPRESSION";
    public static final String ER_EMPTY_XPATH_RESULT = "ER_EMPTY_XPATH_RESULT";
    public static final String ER_ERROR_OCCURED = "ER_ERROR_OCCURED";
    public static final String ER_EXPECTED_BUT_FOUND = "ER_EXPECTED_BUT_FOUND";
    public static final String ER_EXPECTED_DOUBLE_QUOTE = "ER_EXPECTED_DOUBLE_QUOTE";
    public static final String ER_EXPECTED_LOC_PATH = "ER_EXPECTED_LOC_PATH";
    public static final String ER_EXPECTED_LOC_PATH_AT_END_EXPR = "ER_EXPECTED_LOC_PATH_AT_END_EXPR";
    public static final String ER_EXPECTED_LOC_STEP = "ER_EXPECTED_LOC_STEP";
    public static final String ER_EXPECTED_MATCH_PATTERN = "ER_EXPECTED_MATCH_PATTERN";
    public static final String ER_EXPECTED_NODE_TEST = "ER_EXPECTED_NODE_TEST";
    public static final String ER_EXPECTED_REL_LOC_PATH = "ER_EXPECTED_REL_LOC_PATH";
    public static final String ER_EXPECTED_REL_PATH_PATTERN = "ER_EXPECTED_REL_PATH_PATTERN";
    public static final String ER_EXPECTED_SINGLE_QUOTE = "ER_EXPECTED_SINGLE_QUOTE";
    public static final String ER_EXPECTED_STEP_PATTERN = "ER_EXPECTED_STEP_PATTERN";
    public static final String ER_EXTENSION_FUNCTION_CANNOT_BE_INVOKED = "ER_EXTENSION_FUNCTION_CANNOT_BE_INVOKED";
    public static final String ER_EXTRA_ILLEGAL_TOKENS = "ER_EXTRA_ILLEGAL_TOKENS";
    public static final String ER_FASTSTRINGBUFFER_CANNOT_BE_NULL = "ER_FASTSTRINGBUFFER_CANNOT_BE_NULL";
    public static final String ER_FEATURE_NAME_NULL = "ER_FEATURE_NAME_NULL";
    public static final String ER_FEATURE_UNKNOWN = "ER_FEATURE_UNKNOWN";
    public static final String ER_FOUND_COMMA_BUT_NO_FOLLOWING_ARG = "ER_FOUND_COMMA_BUT_NO_FOLLOWING_ARG";
    public static final String ER_FOUND_COMMA_BUT_NO_PRECEDING_ARG = "ER_FOUND_COMMA_BUT_NO_PRECEDING_ARG";
    public static final String ER_FSB_CANNOT_TAKE_STRING = "ER_FSB_CANNOT_TAKE_STRING";
    public static final String ER_FSB_NOT_SUPPORTED_XSTRINGFORCHARS = "ER_FSB_NOT_SUPPORTED_XSTRINGFORCHARS";
    public static final String ER_FUNCTION_TOKEN_NOT_FOUND = "ER_FUNCTION_TOKEN_NOT_FOUND";
    public static final String ER_GETTING_NULL_FEATURE = "ER_GETTING_NULL_FEATURE";
    public static final String ER_GETTING_UNKNOWN_FEATURE = "ER_GETTING_UNKNOWN_FEATURE";
    public static final String ER_IGNORABLE_WHITESPACE_NOT_HANDLED = "ER_IGNORABLE_WHITESPACE_NOT_HANDLED";
    public static final String ER_ILLEGAL_AXIS_NAME = "ER_ILLEGAL_AXIS_NAME";
    public static final String ER_ILLEGAL_VARIABLE_REFERENCE = "ER_ILLEGAL_VARIABLE_REFERENCE";
    public static final String ER_INCOMPATIBLE_TYPES = "ER_INCOMPATIBLE_TYPES";
    public static final String ER_INCORRECT_ARG_LENGTH = "ER_INCORRECT_ARG_LENGTH";
    public static final String ER_INCORRECT_PROGRAMMER_ASSERTION = "ER_INCORRECT_PROGRAMMER_ASSERTION";
    public static final String ER_INVALID_UTF16_SURROGATE = "ER_INVALID_UTF16_SURROGATE";
    public static final String ER_INVALID_XPATH_TYPE = "ER_INVALID_XPATH_TYPE";
    public static final String ER_KEY_HAS_TOO_MANY_ARGS = "ER_KEY_HAS_TOO_MANY_ARGS";
    public static final String ER_LOCALNAME_HAS_TOO_MANY_ARGS = "ER_LOCALNAME_HAS_TOO_MANY_ARGS";
    public static final String ER_NAMESPACEAXIS_NOT_IMPLEMENTED = "ER_NAMESPACEAXIS_NOT_IMPLEMENTED";
    public static final String ER_NAMESPACEURI_HAS_TOO_MANY_ARGS = "ER_NAMESPACEURI_HAS_TOO_MANY_ARGS";
    public static final String ER_NAME_HAS_TOO_MANY_ARGS = "ER_NAME_HAS_TOO_MANY_ARGS";
    public static final String ER_NODESETDTM_CANNOT_INDEX = "ER_NODESETDTM_CANNOT_INDEX";
    public static final String ER_NODESETDTM_CANNOT_ITERATE = "ER_NODESETDTM_CANNOT_ITERATE";
    public static final String ER_NODESETDTM_NOT_MUTABLE = "ER_NODESETDTM_NOT_MUTABLE";
    public static final String ER_NODESET_CANNOT_INDEX = "ER_NODESET_CANNOT_INDEX";
    public static final String ER_NODESET_CANNOT_ITERATE = "ER_NODESET_CANNOT_ITERATE";
    public static final String ER_NODESET_NOT_MUTABLE = "ER_NODESET_NOT_MUTABLE";
    public static final String ER_NON_ITERATOR_TYPE = "ER_NON_ITERATOR_TYPE";
    public static final String ER_NON_SNAPSHOT_TYPE = "ER_NON_SNAPSHOT_TYPE";
    public static final String ER_NORMALIZESPACE_HAS_TOO_MANY_ARGS = "ER_NORMALIZESPACE_HAS_TOO_MANY_ARGS";
    public static final String ER_NULL_ERROR_HANDLER = "ER_NULL_ERROR_HANDLER";
    public static final String ER_NULL_RESOLVER = "ER_NULL_RESOLVER";
    public static final String ER_NULL_XPATH_FUNCTION_RESOLVER = "ER_NULL_XPATH_FUNCTION_RESOLVER";
    public static final String ER_NULL_XPATH_VARIABLE_RESOLVER = "ER_NULL_XPATH_VARIABLE_RESOLVER";
    public static final String ER_NUMBER_HAS_TOO_MANY_ARGS = "ER_NUMBER_HAS_TOO_MANY_ARGS";
    public static final String ER_NUM_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER = "ER_NUM_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER";
    public static final String ER_OBJECT_MODEL_EMPTY = "ER_OBJECT_MODEL_EMPTY";
    public static final String ER_OBJECT_MODEL_NULL = "ER_OBJECT_MODEL_NULL";
    public static final String ER_OIERROR = "ER_OIERROR";
    public static final String ER_ONLY_ALLOWS = "ER_ONLY_ALLOWS";
    public static final String ER_PARSE_NOT_SUPPORTED = "ER_PARSE_NOT_SUPPORTED";
    public static final String ER_PATTERN_LITERAL_NEEDS_BE_QUOTED = "ER_PATTERN_LITERAL_NEEDS_BE_QUOTED";
    public static final String ER_PREDICATE_ILLEGAL_SYNTAX = "ER_PREDICATE_ILLEGAL_SYNTAX";
    public static final String ER_PREFIX_MUST_RESOLVE = "ER_PREFIX_MUST_RESOLVE";
    public static final String ER_PROBLEM_IN_DTM_NEXTSIBLING = "ER_PROBLEM_IN_DTM_NEXTSIBLING";
    public static final String ER_PROG_ASSERT_UNKNOWN_OPCODE = "ER_PROG_ASSERT_UNKNOWN_OPCODE";
    public static final String ER_RESOLVE_VARIABLE_RETURNS_NULL = "ER_RESOLVE_VARIABLE_RETURNS_NULL";
    public static final String ER_RTF_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER = "ER_RTF_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER";
    public static final String ER_SAX_API_NOT_HANDLED = "ER_SAX_API_NOT_HANDLED";
    public static final String ER_SETDOMFACTORY_NOT_SUPPORTED = "ER_SETDOMFACTORY_NOT_SUPPORTED";
    public static final String ER_SETTING_WALKER_ROOT_TO_NULL = "ER_SETTING_WALKER_ROOT_TO_NULL";
    public static final String ER_SOURCE_RETURN_TYPE_CANNOT_BE_NULL = "ER_SOURCE_RETURN_TYPE_CANNOT_BE_NULL";
    public static final String ER_STRINGLENGTH_HAS_TOO_MANY_ARGS = "ER_STRINGLENGTH_HAS_TOO_MANY_ARGS";
    public static final String ER_STRING_HAS_TOO_MANY_ARGS = "ER_STRING_HAS_TOO_MANY_ARGS";
    public static final String ER_STR_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER = "ER_STR_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER";
    public static final String ER_TRANSLATE_TAKES_3_ARGS = "ER_TRANSLATE_TAKES_3_ARGS";
    public static final String ER_TWO_OR_THREE = "ER_TWO_OR_THREE";
    public static final String ER_UNKNOWN_AXIS = "ER_UNKNOWN_AXIS";
    public static final String ER_UNKNOWN_MATCH_OPERATION = "ER_UNKNOWN_MATCH_OPERATION";
    public static final String ER_UNKNOWN_NODETYPE = "ER_UNKNOWN_NODETYPE";
    public static final String ER_UNKNOWN_OPCODE = "ER_UNKNOWN_OPCODE";
    public static final String ER_UNKNOWN_STEP = "ER_UNKNOWN_STEP";
    public static final String ER_UNPARSEDENTITYURI_TAKES_1_ARG = "ER_UNPARSEDENTITYURI_TAKES_1_ARG";
    public static final String ER_UNSUPPORTED_ENCODING = "ER_UNSUPPORTED_ENCODING";
    public static final String ER_UNSUPPORTED_RETURN_TYPE = "ER_UNSUPPORTED_RETURN_TYPE";
    public static final String ER_VARIABLE_ACCESSED_BEFORE_BIND = "ER_VARIABLE_ACCESSED_BEFORE_BIND";
    public static final String ER_VAR_NOT_RESOLVABLE = "ER_VAR_NOT_RESOLVABLE";
    public static final String ER_WRONG_DOCUMENT = "ER_WRONG_DOCUMENT";
    public static final String ER_WRONG_NODETYPE = "ER_WRONG_NODETYPE";
    public static final String ER_XERCES_CANNOT_HANDLE_NODES = "ER_XERCES_CANNOT_HANDLE_NODES";
    public static final String ER_XERCES_PARSE_ERROR = "ER_XERCES_PARSE_ERROR";
    public static final String ER_XERCES_PARSE_ERROR_DETAILS = "ER_XERCES_PARSE_ERROR_DETAILS";
    public static final String ER_XPATH_ERROR = "ER_XPATH_ERROR";
    public static final String ER_XPATH_READOBJECT = "ER_XPATH_READOBJECT";
    public static final String ER_XSTRINGFORCHARS_CANNOT_TAKE_STRING = "ER_XSTRINGFORCHARS_CANNOT_TAKE_STRING";
    public static final String ER_XSTR_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER = "ER_XSTR_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER";
    public static final String ER_ZERO_OR_ONE = "ER_ZERO_OR_ONE";
    public static final String FORMAT_FAILED = "FORMAT_FAILED";
    public static final String QUERY_HEADER = "PATTERN ";
    public static final String WARNING_HEADER = "Warning: ";
    public static final String WG_CANNOT_MAKE_URL_FROM = "WG_CANNOT_MAKE_URL_FROM";
    public static final String WG_COULDNOT_FIND_FUNCTION = "WG_COULDNOT_FIND_FUNCTION";
    public static final String WG_DONT_DO_ANYTHING_WITH_NS = "WG_DONT_DO_ANYTHING_WITH_NS";
    public static final String WG_EXPAND_ENTITIES_NOT_SUPPORTED = "WG_EXPAND_ENTITIES_NOT_SUPPORTED";
    public static final String WG_FUNCTION_TOKEN_NOT_FOUND = "WG_FUNCTION_TOKEN_NOT_FOUND";
    public static final String WG_ILLEGAL_VARIABLE_REFERENCE = "WG_ILLEGAL_VARIABLE_REFERENCE";
    public static final String WG_LOCALE_NAME_NOT_HANDLED = "WG_LOCALE_NAME_NOT_HANDLED";
    public static final String WG_NEED_DERIVED_OBJECT_TO_IMPLEMENT_NODETEST = "WG_NEED_DERIVED_OBJECT_TO_IMPLEMENT_NODETEST";
    public static final String WG_PROPERTY_NOT_SUPPORTED = "WG_PROPERTY_NOT_SUPPORTED";
    public static final String WG_QUO_NO_LONGER_DEFINED = "WG_QUO_NO_LONGER_DEFINED";
    public static final String WG_SECURITY_EXCEPTION = "WG_SECURITY_EXCEPTION";
    public static final String WG_UNSUPPORTED_ENCODING = "WG_UNSUPPORTED_ENCODING";
    public static final String XML_HEADER = "XML ";
    public static final String XSL_HEADER = "XSL ";

    private static final String getResourceSuffix(Locale object) {
        CharSequence charSequence = new StringBuilder();
        charSequence.append("_");
        charSequence.append(((Locale)object).getLanguage());
        charSequence = charSequence.toString();
        String string = ((Locale)object).getCountry();
        object = charSequence;
        if (string.equals("TW")) {
            object = new StringBuilder();
            ((StringBuilder)object).append((String)charSequence);
            ((StringBuilder)object).append("_");
            ((StringBuilder)object).append(string);
            object = ((StringBuilder)object).toString();
        }
        return object;
    }

    public static final XPATHErrorResources loadResourceBundle(String string) throws MissingResourceException {
        Locale locale = Locale.getDefault();
        String string2 = XPATHErrorResources.getResourceSuffix(locale);
        try {
            Object object = new StringBuilder();
            ((StringBuilder)object).append(string);
            ((StringBuilder)object).append(string2);
            object = (XPATHErrorResources)ResourceBundle.getBundle(((StringBuilder)object).toString(), locale);
            return object;
        }
        catch (MissingResourceException missingResourceException) {
            try {
                Object object = new Locale("en", "US");
                object = (XPATHErrorResources)ResourceBundle.getBundle(string, (Locale)object);
                return object;
            }
            catch (MissingResourceException missingResourceException2) {
                throw new MissingResourceException("Could not load any resource bundles.", string, "");
            }
        }
    }

    @Override
    public Object[][] getContents() {
        Object[] arrobject = new Object[]{ERROR0000, "{0}"};
        Object[] arrobject2 = new Object[]{ER_CURRENT_NOT_ALLOWED_IN_MATCH, "The current() function is not allowed in a match pattern!"};
        Object[] arrobject3 = new Object[]{ER_CURRENT_TAKES_NO_ARGS, "The current() function does not accept arguments!"};
        Object[] arrobject4 = new Object[]{ER_DOCUMENT_REPLACED, "document() function implementation has been replaced by org.apache.xalan.xslt.FuncDocument!"};
        Object[] arrobject5 = new Object[]{ER_CONTEXT_HAS_NO_OWNERDOC, "context does not have an owner document!"};
        Object[] arrobject6 = new Object[]{ER_LOCALNAME_HAS_TOO_MANY_ARGS, "local-name() has too many arguments."};
        Object[] arrobject7 = new Object[]{ER_NAMESPACEURI_HAS_TOO_MANY_ARGS, "namespace-uri() has too many arguments."};
        Object[] arrobject8 = new Object[]{ER_NORMALIZESPACE_HAS_TOO_MANY_ARGS, "normalize-space() has too many arguments."};
        Object[] arrobject9 = new Object[]{ER_NUMBER_HAS_TOO_MANY_ARGS, "number() has too many arguments."};
        Object[] arrobject10 = new Object[]{ER_NAME_HAS_TOO_MANY_ARGS, "name() has too many arguments."};
        Object[] arrobject11 = new Object[]{ER_STRING_HAS_TOO_MANY_ARGS, "string() has too many arguments."};
        Object[] arrobject12 = new Object[]{ER_STRINGLENGTH_HAS_TOO_MANY_ARGS, "string-length() has too many arguments."};
        Object[] arrobject13 = new Object[]{ER_TRANSLATE_TAKES_3_ARGS, "The translate() function takes three arguments!"};
        Object[] arrobject14 = new Object[]{ER_UNPARSEDENTITYURI_TAKES_1_ARG, "The unparsed-entity-uri function should take one argument!"};
        Object[] arrobject15 = new Object[]{ER_NAMESPACEAXIS_NOT_IMPLEMENTED, "namespace axis not implemented yet!"};
        Object[] arrobject16 = new Object[]{ER_UNKNOWN_AXIS, "unknown axis: {0}"};
        Object[] arrobject17 = new Object[]{ER_UNKNOWN_MATCH_OPERATION, "unknown match operation!"};
        Object[] arrobject18 = new Object[]{ER_INCORRECT_ARG_LENGTH, "Arg length of processing-instruction() node test is incorrect!"};
        Object[] arrobject19 = new Object[]{ER_CANT_CONVERT_TO_NODELIST, "Can not convert {0} to a NodeList!"};
        Object[] arrobject20 = new Object[]{ER_CANT_CONVERT_TO_MUTABLENODELIST, "Can not convert {0} to a NodeSetDTM!"};
        Object[] arrobject21 = new Object[]{ER_CANT_CONVERT_TO_TYPE, "Can not convert {0} to a type#{1}"};
        Object[] arrobject22 = new Object[]{ER_EXPECTED_MATCH_PATTERN, "Expected match pattern in getMatchScore!"};
        Object[] arrobject23 = new Object[]{ER_COULDNOT_GET_VAR_NAMED, "Could not get variable named {0}"};
        Object[] arrobject24 = new Object[]{ER_UNKNOWN_OPCODE, "ERROR! Unknown op code: {0}"};
        Object[] arrobject25 = new Object[]{ER_EXTRA_ILLEGAL_TOKENS, "Extra illegal tokens: {0}"};
        Object[] arrobject26 = new Object[]{ER_EXPECTED_DOUBLE_QUOTE, "misquoted literal... expected double quote!"};
        Object[] arrobject27 = new Object[]{ER_EXPECTED_SINGLE_QUOTE, "misquoted literal... expected single quote!"};
        Object[] arrobject28 = new Object[]{ER_EMPTY_EXPRESSION, "Empty expression!"};
        Object[] arrobject29 = new Object[]{ER_EXPECTED_BUT_FOUND, "Expected {0}, but found: {1}"};
        Object[] arrobject30 = new Object[]{ER_INCORRECT_PROGRAMMER_ASSERTION, "Programmer assertion is incorrect! - {0}"};
        Object[] arrobject31 = new Object[]{ER_BOOLEAN_ARG_NO_LONGER_OPTIONAL, "boolean(...) argument is no longer optional with 19990709 XPath draft."};
        Object[] arrobject32 = new Object[]{ER_FOUND_COMMA_BUT_NO_PRECEDING_ARG, "Found ',' but no preceding argument!"};
        Object[] arrobject33 = new Object[]{ER_FOUND_COMMA_BUT_NO_FOLLOWING_ARG, "Found ',' but no following argument!"};
        Object[] arrobject34 = new Object[]{ER_ILLEGAL_AXIS_NAME, "illegal axis name: {0}"};
        Object[] arrobject35 = new Object[]{ER_UNKNOWN_NODETYPE, "Unknown nodetype: {0}"};
        Object[] arrobject36 = new Object[]{ER_PATTERN_LITERAL_NEEDS_BE_QUOTED, "Pattern literal ({0}) needs to be quoted!"};
        Object[] arrobject37 = new Object[]{ER_COULDNOT_BE_FORMATTED_TO_NUMBER, "{0} could not be formatted to a number!"};
        Object[] arrobject38 = new Object[]{ER_COULDNOT_CREATE_XMLPROCESSORLIAISON, "Could not create XML TransformerFactory Liaison: {0}"};
        Object[] arrobject39 = new Object[]{ER_DIDNOT_FIND_XPATH_SELECT_EXP, "Error! Did not find xpath select expression (-select)."};
        Object[] arrobject40 = new Object[]{ER_COULDNOT_FIND_ENDOP_AFTER_OPLOCATIONPATH, "ERROR! Could not find ENDOP after OP_LOCATIONPATH"};
        Object[] arrobject41 = new Object[]{ER_ERROR_OCCURED, "Error occured!"};
        Object[] arrobject42 = new Object[]{ER_ILLEGAL_VARIABLE_REFERENCE, "VariableReference given for variable out of context or without definition!  Name = {0}"};
        Object[] arrobject43 = new Object[]{ER_AXES_NOT_ALLOWED, "Only child:: and attribute:: axes are allowed in match patterns!  Offending axes = {0}"};
        Object[] arrobject44 = new Object[]{ER_COUNT_TAKES_1_ARG, "The count function should take one argument!"};
        Object[] arrobject45 = new Object[]{ER_COULDNOT_FIND_FUNCTION, "Could not find function: {0}"};
        Object[] arrobject46 = new Object[]{ER_UNSUPPORTED_ENCODING, "Unsupported encoding: {0}"};
        Object[] arrobject47 = new Object[]{ER_PROBLEM_IN_DTM_NEXTSIBLING, "Problem occured in DTM in getNextSibling... trying to recover"};
        Object[] arrobject48 = new Object[]{ER_CANNOT_WRITE_TO_EMPTYNODELISTIMPL, "Programmer error: EmptyNodeList can not be written to."};
        Object[] arrobject49 = new Object[]{ER_SETDOMFACTORY_NOT_SUPPORTED, "setDOMFactory is not supported by XPathContext!"};
        Object[] arrobject50 = new Object[]{ER_PREFIX_MUST_RESOLVE, "Prefix must resolve to a namespace: {0}"};
        Object[] arrobject51 = new Object[]{ER_PARSE_NOT_SUPPORTED, "parse (InputSource source) not supported in XPathContext! Can not open {0}"};
        Object[] arrobject52 = new Object[]{ER_SAX_API_NOT_HANDLED, "SAX API characters(char ch[]... not handled by the DTM!"};
        Object[] arrobject53 = new Object[]{ER_DTM_CANNOT_HANDLE_NODES, "DTMLiaison can not handle nodes of type {0}"};
        Object[] arrobject54 = new Object[]{ER_XERCES_CANNOT_HANDLE_NODES, "DOM2Helper can not handle nodes of type {0}"};
        Object[] arrobject55 = new Object[]{ER_XERCES_PARSE_ERROR_DETAILS, "DOM2Helper.parse error: SystemID - {0} line - {1}"};
        Object[] arrobject56 = new Object[]{ER_XERCES_PARSE_ERROR, "DOM2Helper.parse error"};
        Object[] arrobject57 = new Object[]{ER_INVALID_UTF16_SURROGATE, "Invalid UTF-16 surrogate detected: {0} ?"};
        Object[] arrobject58 = new Object[]{ER_OIERROR, "IO error"};
        Object[] arrobject59 = new Object[]{ER_XPATH_READOBJECT, "In XPath.readObject: {0}"};
        Object[] arrobject60 = new Object[]{ER_FUNCTION_TOKEN_NOT_FOUND, "function token not found."};
        Object[] arrobject61 = new Object[]{ER_CANNOT_DEAL_XPATH_TYPE, "Can not deal with XPath type: {0}"};
        Object[] arrobject62 = new Object[]{ER_NODESET_NOT_MUTABLE, "This NodeSet is not mutable"};
        Object[] arrobject63 = new Object[]{ER_VAR_NOT_RESOLVABLE, "Variable not resolvable: {0}"};
        Object[] arrobject64 = new Object[]{ER_NULL_ERROR_HANDLER, "Null error handler"};
        Object[] arrobject65 = new Object[]{ER_PROG_ASSERT_UNKNOWN_OPCODE, "Programmer''s assertion: unknown opcode: {0}"};
        Object[] arrobject66 = new Object[]{ER_ZERO_OR_ONE, "0 or 1"};
        Object[] arrobject67 = new Object[]{ER_RTF_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER, "rtf() not supported by XRTreeFragSelectWrapper"};
        Object[] arrobject68 = new Object[]{ER_RTF_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER, "asNodeIterator() not supported by XRTreeFragSelectWrapper"};
        Object[] arrobject69 = new Object[]{ER_DETACH_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER, "detach() not supported by XRTreeFragSelectWrapper"};
        Object[] arrobject70 = new Object[]{ER_XSTR_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER, "xstr() not supported by XRTreeFragSelectWrapper"};
        Object[] arrobject71 = new Object[]{ER_STR_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER, "str() not supported by XRTreeFragSelectWrapper"};
        Object[] arrobject72 = new Object[]{ER_COULD_NOT_FIND_VAR, "Could not find variable with the name of {0}"};
        Object[] arrobject73 = new Object[]{ER_XSTRINGFORCHARS_CANNOT_TAKE_STRING, "XStringForChars can not take a string for an argument"};
        Object[] arrobject74 = new Object[]{ER_FASTSTRINGBUFFER_CANNOT_BE_NULL, "The FastStringBuffer argument can not be null"};
        Object[] arrobject75 = new Object[]{ER_TWO_OR_THREE, "2 or 3"};
        Object[] arrobject76 = new Object[]{ER_SETTING_WALKER_ROOT_TO_NULL, "\n !!!! Error! Setting the root of a walker to null!!!"};
        Object[] arrobject77 = new Object[]{ER_NODESETDTM_CANNOT_ITERATE, "This NodeSetDTM can not iterate to a previous node!"};
        Object[] arrobject78 = new Object[]{ER_NODESET_CANNOT_ITERATE, "This NodeSet can not iterate to a previous node!"};
        Object[] arrobject79 = new Object[]{ER_NODESETDTM_CANNOT_INDEX, "This NodeSetDTM can not do indexing or counting functions!"};
        Object[] arrobject80 = new Object[]{ER_ONLY_ALLOWS, "{0} only allows {1} arguments"};
        Object[] arrobject81 = new Object[]{ER_UNKNOWN_STEP, "Programmer''s assertion in getNextStepPos: unknown stepType: {0}"};
        Object[] arrobject82 = new Object[]{ER_EXPECTED_REL_LOC_PATH, "A relative location path was expected following the '/' or '//' token."};
        Object[] arrobject83 = new Object[]{ER_EXPECTED_LOC_PATH, "A location path was expected, but the following token was encountered:  {0}"};
        Object[] arrobject84 = new Object[]{ER_EXPECTED_LOC_PATH_AT_END_EXPR, "A location path was expected, but the end of the XPath expression was found instead."};
        Object[] arrobject85 = new Object[]{ER_EXPECTED_LOC_STEP, "A location step was expected following the '/' or '//' token."};
        Object[] arrobject86 = new Object[]{ER_EXPECTED_NODE_TEST, "A node test that matches either NCName:* or QName was expected."};
        Object[] arrobject87 = new Object[]{ER_EXPECTED_STEP_PATTERN, "A step pattern was expected, but '/' was encountered."};
        Object[] arrobject88 = new Object[]{ER_EXPECTED_REL_PATH_PATTERN, "A relative path pattern was expected."};
        Object[] arrobject89 = new Object[]{ER_CANT_CONVERT_TO_BOOLEAN, "The XPathResult of XPath expression ''{0}'' has an XPathResultType of {1} which cannot be converted to a boolean."};
        Object[] arrobject90 = new Object[]{ER_CANT_CONVERT_TO_SINGLENODE, "The XPathResult of XPath expression ''{0}'' has an XPathResultType of {1} which cannot be converted to a single node. The method getSingleNodeValue applies only to types ANY_UNORDERED_NODE_TYPE and FIRST_ORDERED_NODE_TYPE."};
        Object[] arrobject91 = new Object[]{ER_NON_ITERATOR_TYPE, "The method iterateNext cannot be called on the XPathResult of XPath expression ''{0}'' because its XPathResultType is {1}. This method applies only to types UNORDERED_NODE_ITERATOR_TYPE and ORDERED_NODE_ITERATOR_TYPE."};
        Object[] arrobject92 = new Object[]{ER_DOC_MUTATED, "Document mutated since result was returned. Iterator is invalid."};
        Object[] arrobject93 = new Object[]{ER_INVALID_XPATH_TYPE, "Invalid XPath type argument: {0}"};
        Object[] arrobject94 = new Object[]{ER_EMPTY_XPATH_RESULT, "Empty XPath result object"};
        Object[] arrobject95 = new Object[]{ER_INCOMPATIBLE_TYPES, "The XPathResult of XPath expression ''{0}'' has an XPathResultType of {1} which cannot be coerced into the specified XPathResultType of {2}."};
        Object[] arrobject96 = new Object[]{ER_NULL_RESOLVER, "Unable to resolve prefix with null prefix resolver."};
        Object[] arrobject97 = new Object[]{ER_CANT_CONVERT_TO_STRING, "The XPathResult of XPath expression ''{0}'' has an XPathResultType of {1} which cannot be converted to a string."};
        Object[] arrobject98 = new Object[]{ER_NON_SNAPSHOT_TYPE, "The method snapshotItem cannot be called on the XPathResult of XPath expression ''{0}'' because its XPathResultType is {1}. This method applies only to types UNORDERED_NODE_SNAPSHOT_TYPE and ORDERED_NODE_SNAPSHOT_TYPE."};
        Object[] arrobject99 = new Object[]{ER_WRONG_DOCUMENT, "Context node does not belong to the document that is bound to this XPathEvaluator."};
        Object[] arrobject100 = new Object[]{ER_WRONG_NODETYPE, "The context node type is not supported."};
        Object[] arrobject101 = new Object[]{ER_XPATH_ERROR, "Unknown error in XPath."};
        Object[] arrobject102 = new Object[]{ER_CANT_CONVERT_XPATHRESULTTYPE_TO_NUMBER, "The XPathResult of XPath expression ''{0}'' has an XPathResultType of {1} which cannot be converted to a number"};
        Object[] arrobject103 = new Object[]{ER_EXTENSION_FUNCTION_CANNOT_BE_INVOKED, "Extension function: ''{0}'' can not be invoked when the XMLConstants.FEATURE_SECURE_PROCESSING feature is set to true."};
        Object[] arrobject104 = new Object[]{ER_RESOLVE_VARIABLE_RETURNS_NULL, "resolveVariable for variable {0} returning null"};
        Object[] arrobject105 = new Object[]{ER_UNSUPPORTED_RETURN_TYPE, "UnSupported Return Type : {0}"};
        Object[] arrobject106 = new Object[]{ER_SOURCE_RETURN_TYPE_CANNOT_BE_NULL, "Source and/or Return Type can not be null"};
        Object[] arrobject107 = new Object[]{ER_SOURCE_RETURN_TYPE_CANNOT_BE_NULL, "Source and/or Return Type can not be null"};
        Object[] arrobject108 = new Object[]{ER_ARG_CANNOT_BE_NULL, "{0} argument can not be null"};
        Object[] arrobject109 = new Object[]{ER_OBJECT_MODEL_NULL, "{0}#isObjectModelSupported( String objectModel ) cannot be called with objectModel == null"};
        Object[] arrobject110 = new Object[]{ER_OBJECT_MODEL_EMPTY, "{0}#isObjectModelSupported( String objectModel ) cannot be called with objectModel == \"\""};
        Object[] arrobject111 = new Object[]{ER_FEATURE_NAME_NULL, "Trying to set a feature with a null name: {0}#setFeature( null, {1})"};
        Object[] arrobject112 = new Object[]{ER_FEATURE_UNKNOWN, "Trying to set the unknown feature \"{0}\":{1}#setFeature({0},{2})"};
        Object[] arrobject113 = new Object[]{ER_GETTING_NULL_FEATURE, "Trying to get a feature with a null name: {0}#getFeature(null)"};
        Object[] arrobject114 = new Object[]{ER_GETTING_UNKNOWN_FEATURE, "Trying to get the unknown feature \"{0}\":{1}#getFeature({0})"};
        Object[] arrobject115 = new Object[]{ER_NULL_XPATH_FUNCTION_RESOLVER, "Attempting to set a null XPathFunctionResolver:{0}#setXPathFunctionResolver(null)"};
        Object[] arrobject116 = new Object[]{ER_NULL_XPATH_VARIABLE_RESOLVER, "Attempting to set a null XPathVariableResolver:{0}#setXPathVariableResolver(null)"};
        Object[] arrobject117 = new Object[]{WG_LOCALE_NAME_NOT_HANDLED, "locale name in the format-number function not yet handled!"};
        Object[] arrobject118 = new Object[]{WG_PROPERTY_NOT_SUPPORTED, "XSL Property not supported: {0}"};
        Object[] arrobject119 = new Object[]{WG_DONT_DO_ANYTHING_WITH_NS, "Do not currently do anything with namespace {0} in property: {1}"};
        Object[] arrobject120 = new Object[]{WG_SECURITY_EXCEPTION, "SecurityException when trying to access XSL system property: {0}"};
        Object[] arrobject121 = new Object[]{WG_QUO_NO_LONGER_DEFINED, "Old syntax: quo(...) is no longer defined in XPath."};
        Object[] arrobject122 = new Object[]{WG_NEED_DERIVED_OBJECT_TO_IMPLEMENT_NODETEST, "XPath needs a derived object to implement nodeTest!"};
        Object[] arrobject123 = new Object[]{WG_FUNCTION_TOKEN_NOT_FOUND, "function token not found."};
        Object[] arrobject124 = new Object[]{WG_COULDNOT_FIND_FUNCTION, "Could not find function: {0}"};
        Object[] arrobject125 = new Object[]{WG_CANNOT_MAKE_URL_FROM, "Can not make URL from: {0}"};
        Object[] arrobject126 = new Object[]{WG_ILLEGAL_VARIABLE_REFERENCE, "VariableReference given for variable out of context or without definition!  Name = {0}"};
        Object[] arrobject127 = new Object[]{WG_UNSUPPORTED_ENCODING, "Unsupported encoding: {0}"};
        Object[] arrobject128 = new Object[]{"ui_language", "en"};
        Object[] arrobject129 = new Object[]{"help_language", "en"};
        Object[] arrobject130 = new Object[]{"language", "en"};
        Object[] arrobject131 = new Object[]{BAD_CODE, "Parameter to createMessage was out of bounds"};
        Object[] arrobject132 = new Object[]{FORMAT_FAILED, "Exception thrown during messageFormat call"};
        Object[] arrobject133 = new Object[]{"version", ">>>>>>> Xalan Version "};
        Object[] arrobject134 = new Object[]{"version2", "<<<<<<<"};
        Object[] arrobject135 = new Object[]{"yes", "yes"};
        Object[] arrobject136 = new Object[]{"column", "Column #"};
        Object[] arrobject137 = new Object[]{"xsldone", "XSLProcessor: done"};
        Object[] arrobject138 = new Object[]{"optionIN", "   [-in inputXMLURL]"};
        Object[] arrobject139 = new Object[]{"optionSelect", "   [-select xpath expression]"};
        Object[] arrobject140 = new Object[]{"optionMatch", "   [-match match pattern (for match diagnostics)]"};
        Object[] arrobject141 = new Object[]{"noParsermsg1", "XSL Process was not successful."};
        Object[] arrobject142 = new Object[]{"noParsermsg2", "** Could not find parser **"};
        Object[] arrobject143 = new Object[]{"noParsermsg3", "Please check your classpath."};
        Object[] arrobject144 = new Object[]{"noParsermsg4", "If you don't have IBM's XML Parser for Java, you can download it from"};
        Object[] arrobject145 = new Object[]{"gtone", ">1"};
        Object[] arrobject146 = new Object[]{"zero", "0"};
        Object[] arrobject147 = new Object[]{"one", "1"};
        Object[] arrobject148 = new Object[]{"two", "2"};
        Object[] arrobject149 = new Object[]{"three", "3"};
        return new Object[][]{arrobject, arrobject2, arrobject3, arrobject4, arrobject5, arrobject6, arrobject7, arrobject8, arrobject9, arrobject10, arrobject11, arrobject12, arrobject13, arrobject14, arrobject15, arrobject16, arrobject17, arrobject18, {ER_CANT_CONVERT_TO_NUMBER, "Can not convert {0} to a number"}, arrobject19, arrobject20, arrobject21, arrobject22, arrobject23, arrobject24, arrobject25, arrobject26, arrobject27, arrobject28, arrobject29, arrobject30, arrobject31, arrobject32, arrobject33, {ER_PREDICATE_ILLEGAL_SYNTAX, "'..[predicate]' or '.[predicate]' is illegal syntax.  Use 'self::node()[predicate]' instead."}, arrobject34, arrobject35, arrobject36, arrobject37, arrobject38, arrobject39, arrobject40, arrobject41, arrobject42, arrobject43, {ER_KEY_HAS_TOO_MANY_ARGS, "key() has an incorrect number of arguments."}, arrobject44, arrobject45, arrobject46, arrobject47, arrobject48, arrobject49, arrobject50, arrobject51, arrobject52, {ER_IGNORABLE_WHITESPACE_NOT_HANDLED, "ignorableWhitespace(char ch[]... not handled by the DTM!"}, arrobject53, arrobject54, arrobject55, arrobject56, arrobject57, arrobject58, {ER_CANNOT_CREATE_URL, "Cannot create url for: {0}"}, arrobject59, arrobject60, arrobject61, arrobject62, {ER_NODESETDTM_NOT_MUTABLE, "This NodeSetDTM is not mutable"}, arrobject63, arrobject64, arrobject65, arrobject66, arrobject67, arrobject68, arrobject69, {ER_NUM_NOT_SUPPORTED_XRTREEFRAGSELECTWRAPPER, "num() not supported by XRTreeFragSelectWrapper"}, arrobject70, arrobject71, {ER_FSB_NOT_SUPPORTED_XSTRINGFORCHARS, "fsb() not supported for XStringForChars"}, arrobject72, arrobject73, arrobject74, arrobject75, {ER_VARIABLE_ACCESSED_BEFORE_BIND, "Variable accessed before it is bound!"}, {ER_FSB_CANNOT_TAKE_STRING, "XStringForFSB can not take a string for an argument!"}, arrobject76, arrobject77, arrobject78, arrobject79, {ER_NODESET_CANNOT_INDEX, "This NodeSet can not do indexing or counting functions!"}, {ER_CANNOT_CALL_SETSHOULDCACHENODE, "Can not call setShouldCacheNodes after nextNode has been called!"}, arrobject80, arrobject81, arrobject82, arrobject83, arrobject84, arrobject85, arrobject86, arrobject87, arrobject88, arrobject89, arrobject90, {ER_CANT_GET_SNAPSHOT_LENGTH, "The method getSnapshotLength cannot be called on the XPathResult of XPath expression ''{0}'' because its XPathResultType is {1}. This method applies only to types UNORDERED_NODE_SNAPSHOT_TYPE and ORDERED_NODE_SNAPSHOT_TYPE."}, arrobject91, arrobject92, arrobject93, arrobject94, arrobject95, arrobject96, arrobject97, arrobject98, arrobject99, arrobject100, arrobject101, arrobject102, arrobject103, arrobject104, arrobject105, arrobject106, arrobject107, arrobject108, arrobject109, arrobject110, arrobject111, arrobject112, arrobject113, arrobject114, arrobject115, arrobject116, arrobject117, arrobject118, arrobject119, arrobject120, arrobject121, arrobject122, arrobject123, arrobject124, arrobject125, {WG_EXPAND_ENTITIES_NOT_SUPPORTED, "-E option not supported for DTM parser"}, arrobject126, arrobject127, arrobject128, arrobject129, arrobject130, arrobject131, arrobject132, arrobject133, arrobject134, arrobject135, {"line", "Line #"}, arrobject136, arrobject137, {"xpath_option", "xpath options: "}, arrobject138, arrobject139, arrobject140, {"optionAnyExpr", "Or just an xpath expression will do a diagnostic dump"}, arrobject141, arrobject142, arrobject143, arrobject144, {"noParsermsg5", "IBM's AlphaWorks: http://www.alphaworks.ibm.com/formula/xml"}, arrobject145, arrobject146, arrobject147, arrobject148, arrobject149};
    }
}

